apiVersion: apps/v1
kind: Deployment
metadata:
  name: fcg-payments-worker
spec:
  replicas: 1

  selector:
    matchLabels:
      app: fcg-payments-worker

    spec:
      containers:
        - name: fcg-payments-worker
          image: GabrielNatan2001/fcg-payments-worker:latest

          ports:
           - containerPort: 8080

           envFrom:
            - configMapRef:
                name: fcg-payments-worker-config

            - secretRef:
                name: fcg-payments-worker-secret
          
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3